import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('course sources, map, conversation and exam DNA are usable', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.model-badge')).toContainText('混合模式')
  await expect(page.locator('.model-badge svg')).toHaveCount(0)
  await page.locator('.source-chips button').first().click()
  await expect(page.locator('.source-text')).toContainText('[Page')
  await page.getByRole('button', { name: '关闭窗口' }).click()
  await page.locator('.nav-item').filter({ hasText: '知识地图' }).click()
  await expect(page.locator('.map-graph')).toBeVisible()
  await page.locator('.map-node').first().click()
  await expect(page.locator('.map-topic-detail')).toBeVisible()
  await page.getByRole('button', { name: 'Question DNA', exact: true }).click()
  await page.getByRole('button', { name: '分析历年卷', exact: true }).click()
  await expect(page.locator('.artifact-exam-years')).toHaveText('2024–2026')
  await expect(page.locator('.artifact-pattern-row')).toHaveCount(3)
  await page.getByRole('button', { name: /新建学习对话/ }).click()
  await page.getByRole('textbox', { name: '向 Exam Radar 提问' }).fill('Explain F1 score')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.chat-message.assistant')).toBeVisible()
  await expect(page.locator('.chat-message.assistant')).toContainText('F1')
  expect(errors).toEqual([])
})

test('chat routes mock exams and then switches back to analysis', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /新建学习对话/ }).click()
  const composer = page.getByRole('textbox', { name: '向 Exam Radar 提问' })
  await composer.fill('参考这份历年试卷，举一反三生成一份新的模拟考试卷')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const generated = page.locator('.chat-message.assistant').last()
  await expect(generated).toContainText('模拟试卷生成')
  await expect(generated).toContainText('答案与解析')
  await composer.fill('总结这份试卷的高频考点')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const analyzed = page.locator('.chat-message.assistant').last()
  await expect(analyzed).toContainText('考点分析')
})

test('practice updates mastery; editable packs export and share privately', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '练习薄弱点', exact: true }).click()
  await expect(page.locator('.practice-card')).toBeVisible()
  await page.locator('.answer-option input').first().check()
  await page.getByRole('button', { name: '提交答案', exact: true }).click()
  await expect(page.locator('.feedback-score')).toContainText('掌握度')
  await page.getByText('查看参考答案', { exact: true }).click()
  await expect(page.locator('.feedback details[open]')).toBeVisible()
  await page.getByRole('button', { name: '复习资料', exact: true }).click()
  await page.getByRole('button', { name: '生成复习包', exact: true }).click()
  await expect(page.locator('.pack-card')).toHaveCount(1)
  await page.getByRole('button', { name: '编辑复习包', exact: true }).click()
  const editor = page.getByRole('textbox', { name: '编辑复习包 Markdown' })
  await editor.fill((await editor.inputValue()) + '\n\n## My study note\nKeep this revision note.')
  await page.locator('.artifact-save-row button').click()
  await expect(page.getByRole('status')).toContainText('修改已保存')
  const event = page.waitForEvent('download')
  await page.locator('.export-row').getByRole('button', { name: 'Word', exact: true }).click()
  const download = await event
  const bytes = await readFile((await download.path())!)
  expect(bytes.subarray(0, 2).toString()).toBe('PK')
  await page.getByRole('button', { name: '分享课程', exact: true }).click()
  await page.getByRole('button', { name: '创建分享链接', exact: true }).click()
  const link = await page.locator('#share-link').inputValue()
  const peer = await browser.newContext()
  const sharedPage = await peer.newPage()
  await sharedPage.goto(link)
  await expect(sharedPage.locator('.shared-main')).toContainText('Keep this revision note.')
  await expect(sharedPage.locator('.shared-main')).not.toContainText('预计掌握度')
  const token = new URL(link).searchParams.get('share')
  const payload = await (await sharedPage.request.get('/api/shared/' + token)).json()
  expect(JSON.stringify(payload)).not.toContain('"mastery"')
  expect(payload.sessions).toBeUndefined()
  await sharedPage.locator('#comment').fill('A useful revision pack.')
  await sharedPage.getByRole('button', { name: '发表评论', exact: true }).click()
  await expect(sharedPage.locator('.shared-discussion')).toContainText('A useful revision pack.')
  await peer.close()
})

test('create a real course without exam date and upload a source', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新建课程', exact: true }).click()
  await page.locator('#course-name').fill('Browser QA course')
  await page.locator('#course-code').fill('QA101')
  await page.getByRole('dialog').getByRole('button', { name: '创建课程', exact: true }).click()
  await expect(page.locator('.dropzone')).toBeVisible()
  await page.locator('input[type=file]').setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Chapter 1. Model evaluation. Precision equals true positives divided by predicted positives. Recall equals true positives divided by actual positives.') })
  await page.getByRole('button', { name: '上传资料', exact: true }).click()
  await expect(page.locator('.material-list')).toContainText('notes.txt')
  const health = await (await page.request.get('/api/health')).json()
  if (health.mode === 'demo') {
    await page.getByRole('button', { name: '分析课程', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('OPENAI_API_KEY')
  }
  await page.reload()
  await expect(page.locator('.course-list')).toContainText('Browser QA course')
})

test('mobile workspace stays in the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.model-badge')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await expect(page.locator('.sidebar.is-open')).toBeVisible()
  await page.locator('.nav-item').filter({ hasText: '知识地图' }).click()
  await expect(page.locator('.map-graph')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('settings keeps the interface in Chinese and saves the display name', async ({ page }) => {
  await page.goto('/')
  await page.locator('.profile').click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('个人偏好')
  await expect(dialog).not.toContainText('English')
  await expect(dialog).not.toContainText('语言')
  await dialog.locator('#display-name').fill('中文用户')
  await dialog.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.getByRole('button', { name: '新建学习对话', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  expect(await page.evaluate(() => localStorage.getItem('exam-radar-language'))).toBeNull()
  await page.reload()
  await expect(page.getByRole('button', { name: '新建学习对话', exact: true })).toBeVisible()
  await page.locator('.profile').click()
  await expect(page.getByRole('dialog').locator('#display-name')).toHaveValue('中文用户')
})
